POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "Ganesh",
  "password": "gopal78"
}

####


POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "Ganesh",
  "password": "gopal78"
}
###
POST http://localhost:3000/posts/ 
Content-Type: application/json 

{
    "user_id":1,
    "id":1,
    "title":"gopal",
    "body":"I am happy"
}

###
GET http://localhost:3000/getPosts/
